[project]
name = "clicod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "google>=3.0.0",
    "google-genai>=1.30.0",
    "rich>=14.1.0",
]
